/**
 * Profiles the three source CSVs so cleaning rules are based on what's
 * actually in the data, not guesses. Prints a markdown report to stdout:
 *
 *   npm run profile > DATA_NOTES.md
 */
import { readFileSync } from "node:fs";
import { parse } from "csv-parse/sync";

type Row = Record<string, string>;

function load(file: string): Row[] {
  return parse(readFileSync(`data/${file}`, "utf8"), {
    columns: true,
    skip_empty_lines: true,
    relax_column_count: true,
    bom: true,
  });
}

function counts(values: string[]): Map<string, number> {
  const m = new Map<string, number>();
  for (const v of values) m.set(v, (m.get(v) ?? 0) + 1);
  return new Map([...m].sort((a, b) => b[1] - a[1]));
}

function table(m: Map<string, number>, limit = 40) {
  const rows = [...m].slice(0, limit);
  console.log("| value | count |\n| --- | --- |");
  for (const [k, n] of rows) console.log(`| \`${k === "" ? "(empty)" : k}\` | ${n} |`);
  if (m.size > limit) console.log(`| … ${m.size - limit} more | |`);
  console.log();
}

/** Classify a date string by shape so every format present is visible. */
function dateShape(s: string): string {
  if (s.trim() === "") return "(empty)";
  return s
    .trim()
    .replace(/[0-9]/g, "9")
    .replace(/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\b/i, "Mon");
}

function emailIssues(emails: string[]) {
  const issues = {
    empty: 0,
    leadingOrTrailingSpace: 0,
    uppercase: 0,
    noAt: 0,
    plusAlias: 0,
    multipleAt: 0,
    invalidChars: 0,
  };
  for (const e of emails) {
    if (e === "") { issues.empty++; continue; }
    if (e !== e.trim()) issues.leadingOrTrailingSpace++;
    if (e !== e.toLowerCase()) issues.uppercase++;
    const at = (e.match(/@/g) ?? []).length;
    if (at === 0) issues.noAt++;
    if (at > 1) issues.multipleAt++;
    if (/\+/.test(e.split("@")[0] ?? "")) issues.plusAlias++;
    if (!/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(e.trim())) issues.invalidChars++;
  }
  return issues;
}

function section(title: string) {
  console.log(`\n## ${title}\n`);
}

function kv(obj: Record<string, number | string>) {
  console.log("| metric | value |\n| --- | --- |");
  for (const [k, v] of Object.entries(obj)) console.log(`| ${k} | ${v} |`);
  console.log();
}

console.log("# DATA_NOTES — CSV profile\n");
console.log("Generated by `npm run profile`. Reference date for all time math: 2026-09-28.\n");

// ---------------------------------------------------------------- subscribers
const subs = load("subscribers.csv");
section("subscribers.csv");
console.log(`Columns: ${Object.keys(subs[0]).map((c) => `\`${c}\``).join(", ")}\n`);
const subEmails = subs.map((r) => r.email ?? "");
const normSub = subEmails.map((e) => e.trim().toLowerCase());
kv({
  rows: subs.length,
  "distinct raw emails": new Set(subEmails).size,
  "distinct normalized emails": new Set(normSub).size,
  "duplicate rows after normalize": subs.length - new Set(normSub).size,
});
console.log("### Email issues\n");
kv(emailIssues(subEmails));
console.log("### status values (raw)\n");
table(counts(subs.map((r) => r.status ?? "")));
console.log("### acquisition_source values (raw)\n");
table(counts(subs.map((r) => r.acquisition_source ?? "")));
console.log("### signup_date formats\n");
table(counts(subs.map((r) => dateShape(r.signup_date ?? ""))));
console.log("### last_open_date formats\n");
table(counts(subs.map((r) => dateShape(r.last_open_date ?? ""))));
console.log("### Sample unusual dates\n");
const odd = subs
  .flatMap((r) => [r.signup_date, r.last_open_date])
  .filter((d) => d && !/^\d{4}-\d{2}-\d{2}$/.test(d.trim()));
table(counts(odd), 15);

// Duplicate detail: how do the dup rows differ?
const byEmail = new Map<string, Row[]>();
subs.forEach((r) => {
  const k = (r.email ?? "").trim().toLowerCase();
  byEmail.set(k, [...(byEmail.get(k) ?? []), r]);
});
const dups = [...byEmail.values()].filter((g) => g.length > 1);
console.log("### Duplicate groups\n");
kv({
  "emails with >1 row": dups.length,
  "groups with differing status": dups.filter((g) => new Set(g.map((r) => r.status)).size > 1).length,
  "groups with differing source": dups.filter((g) => new Set(g.map((r) => r.acquisition_source)).size > 1).length,
  "groups with differing signup_date": dups.filter((g) => new Set(g.map((r) => r.signup_date)).size > 1).length,
  "groups with differing last_open_date": dups.filter((g) => new Set(g.map((r) => r.last_open_date)).size > 1).length,
  "groups differing only by email case/space": dups.filter((g) => new Set(g.map((r) => r.email)).size > 1).length,
});
console.log("Example groups:\n");
console.log("```");
dups.slice(0, 5).forEach((g) => g.forEach((r) => console.log(JSON.stringify(r))));
console.log("```\n");

// ---------------------------------------------------------------- web events
const web = load("web_events.csv");
section("web_events.csv");
console.log(`Columns: ${Object.keys(web[0]).map((c) => `\`${c}\``).join(", ")}\n`);
const webEmails = web.map((r) => r.email ?? "");
const webWithEmail = webEmails.filter((e) => e.trim() !== "");
const normWeb = new Set(webWithEmail.map((e) => e.trim().toLowerCase()));
const subSet = new Set(normSub);
kv({
  rows: web.length,
  "distinct visitor_id": new Set(web.map((r) => r.visitor_id)).size,
  "rows with email": webWithEmail.length,
  "distinct emails": normWeb.size,
  "emails matching a subscriber": [...normWeb].filter((e) => subSet.has(e)).length,
  "emails NOT matching any subscriber": [...normWeb].filter((e) => !subSet.has(e)).length,
  "distinct pages": new Set(web.map((r) => r.page)).size,
});
console.log("### Email issues (non-empty only)\n");
kv(emailIssues(webWithEmail));
console.log("### utm_source values (raw)\n");
table(counts(web.map((r) => r.utm_source ?? "")));
console.log("### timestamp formats\n");
table(counts(web.map((r) => dateShape(r.timestamp ?? ""))));
console.log("### Top pages\n");
table(counts(web.map((r) => r.page ?? "")), 25);

// Visitor ↔ email stitching stats
const visitorEmails = new Map<string, Set<string>>();
web.forEach((r) => {
  const e = (r.email ?? "").trim().toLowerCase();
  if (!e) return;
  visitorEmails.set(r.visitor_id, new Set([...(visitorEmails.get(r.visitor_id) ?? []), e]));
});
const emailVisitors = new Map<string, Set<string>>();
visitorEmails.forEach((es, v) => es.forEach((e) => emailVisitors.set(e, new Set([...(emailVisitors.get(e) ?? []), v]))));
console.log("### Identity stitching\n");
kv({
  "visitors with ≥1 email": visitorEmails.size,
  "visitors with >1 distinct email (shared device?)": [...visitorEmails.values()].filter((s) => s.size > 1).length,
  "emails seen on >1 visitor": [...emailVisitors.values()].filter((s) => s.size > 1).length,
  "events on visitors that have an email (inherit link)": web.filter((r) => visitorEmails.has(r.visitor_id)).length,
});

// ---------------------------------------------------------------- app users
const app = load("app_users.csv");
section("app_users.csv");
console.log(`Columns: ${Object.keys(app[0]).map((c) => `\`${c}\``).join(", ")}\n`);
const appEmails = app.map((r) => r.email ?? "");
const normApp = appEmails.map((e) => e.trim().toLowerCase());
kv({
  rows: app.length,
  "distinct user_id": new Set(app.map((r) => r.user_id)).size,
  "distinct normalized emails": new Set(normApp).size,
  "emails matching a subscriber": normApp.filter((e) => e && subSet.has(e)).length,
  "emails NOT matching any subscriber": normApp.filter((e) => e && !subSet.has(e)).length,
});
console.log("### Email issues\n");
kv(emailIssues(appEmails));
console.log("### created_at formats\n");
table(counts(app.map((r) => dateShape(r.created_at ?? ""))));
console.log("### user_id shape\n");
table(counts(app.map((r) => dateShape(r.user_id ?? ""))), 5);
